image: node:12

stages:
    - install
    - build
    - quality
    - deploy

install: 
    stage: install
    script:
        - npm install
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 60 mins
        paths:
          - .npm/
          - node_modules/


linting:
    stage: quality
    script:
        - npm run lint
    dependencies:
        - install

testing:
    stage: quality
    script:
        - CI=true npm run test
    dependencies:
        - install

mutation:
    stage: quality
    script:
        - npm run mutate
    dependencies:
        - install

build:
    stage: build
    tags:
        - test-server
    script:
        - npm run build
    dependencies:
        - install

deploy-test:
    tags: test-server
    environment:
        name: test-server
        url: 
    stage: deploy
        - npm install -g serve
        - serve -s build


